export const FETCH_HISTORICAL_SEARCH_SUCCESS = 'FETCH_HISTORICAL_SEARCH_SUCCESS'

export const FETCH_HISTORICAL_SEARCH_FAILURE = 'FETCH_HISTORICAL_SEARCH_FAILURE'

export const FETCH_HISTORICAL_SEARCH_REQUEST = 'FETCH_HISTORICAL_SEARCH_REQUEST'